name: myfirstaction
on: workflow_dispatch
jobs:
  myfirstjob: 
    runs-on: ubuntu-latest
    steps:
    - name: Print "Greetings"
      run: echo "Hello students"
    - name: Print Congratz
      run: echo "From Accenture"
